version: '3.1'
services:
  app: 
    build: .
    container_name: node-app
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/app
  
  mysql:
    container_name: node-mysql
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
        - './:/application'
        - './.docker/mysql/data:/var/lib/mysql'
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=app
    ports:
        - '3306:3306'

  phpmyadmin:
    container_name: node-php_my_admin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1